### ISSUE TITLE
Try again later error on Android 10

### ISSUE THREAD

**Issue by anburocky3** [the-dise/Instander#1]
![Screenshot_2021-09-12-22-30-12-041_com.instander.android.jpg](https://user-images.githubusercontent.com/15264938/132996265-be0ee88b-3bc8-4566-b52b-b23d936f955e.jpg)

**Comment by zahidshaikh08** [comment]
i downgraded to 12.1 and everything just works fine as before...

**Comment by anburocky3** [comment]
@zahidshaikh08 **Downgrading** is not a solution.

Looks like Turning off "Maximize Photo Quality" in Instander settings solved the problem.

For me, I uninstalled and installed it after 2 days and the error didn't show afterward.
